spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.1.5:31833/ps_db
    username: ps_user
    password: SecurePassword
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop



#spring:
#  datasource:
#    url: jdbc:postgresql://192.168.1.5:31833/ps_db
#    username: ps_user
#    password: SecurePassword
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#      hibernate:
#        hbm2ddl:
#          delimiter: ;
#        jdbc:
#          lob:
#            non_contextual_creation: True
#        format_sql: true
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#


  #    config h2
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true